title: Youngho Shin
description: M.A. (completed coursework), Sogang University
theme: minima
google_analytics: G-XYBQXM2P0Z

header_pages:
  - cv.md
  - contact.md

markdown: kramdown
plugins:
  - jekyll-seo-tag
